---
- name: Temporarily enable root SSH on CentOS VM through Proxmox
  hosts: proxmox_servers
  become: true
  gather_facts: false

  vars:
    target_vmids:
      - prompt: "provide proxmox vm id {{ target_vmids }}"

  tasks:
    - name: Enable temporary root SSH
      ansible.builtin.command:
        cmd: >
          qm guest exec {{ item }} --
          bash -lc "
          cat > /etc/ssh/sshd_config.d/99-temp-root-login.conf <<'EOF'
          PermitRootLogin yes
          PasswordAuthentication yes
          EOF
          systemctl restart sshd
          "
      loop: "{{ target_vmids }}"