---
- hosts: centos_servers
  become: true
  tasks:
  - name: install updates centos
    ansible.builtin.dnf:
      update_cache: true

- hosts: proxmox_servers
  become: true
  tasks:
  - name: Update apt repo and cache proxmox
    ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
  
  - name: Run apt dist-upgrade proxmox
    ansible.builtin.apt:
        upgrade: dist

- hosts: windows_servers
  tasks:
  - name: install updates windows
    ansible.windows.win_updates:
      category_names:
        - CriticalUpdates
        - SecurityUpdates
        - Updates
      state: installed
